Updated `todo.txt`. Build error on Travis was probably caused by Travis.
There is still 1 test which does not pass Travis:

[ RUN      ] fbx_file_must_be_loaded_appropriately.rigged_and_animated_cat
Error: uvs is nullptr!
/home/travis/build/nrz/ylikuutio/code/ylikuutio/tests/googletest/test_fbx_loader.cpp:248: Failure
Value of: result
  Actual: false
Expected: true
[  FAILED  ] fbx_file_must_be_loaded_appropriately.rigged_and_animated_cat (325 ms)

	modified:   todo.txt