Bugfix: when crosscompiling for Windows, use `-DASIO_STANDALONE`.
This fixes the bug:

[ 29%] Building CXX object CMakeFiles/ylikuutio.dir/code/ylikuutio/network/tcp_connection.cpp.obj
In file included from /home/someuser/code/ylikuutio/external/asio/asio/include/asio/associated_allocator.hpp:18:0,
                 from /home/someuser/code/ylikuutio/external/asio/asio/include/asio.hpp:18,
                 from /home/someuser/code/ylikuutio/code/ylikuutio/network/tcp_connection.hpp:2,
                 from /home/someuser/code/ylikuutio/code/ylikuutio/network/tcp_connection.cpp:1:
/home/someuser/code/ylikuutio/external/asio/asio/include/asio/detail/config.hpp:26:29: fatal error: boost/config.hpp: No such file or directory
 # include <boost/config.hpp>
                             ^
compilation terminated.
CMakeFiles/ylikuutio.dir/build.make:963: recipe for target 'CMakeFiles/ylikuutio.dir/code/ylikuutio/network/tcp_connection.cpp.obj' failed
make[2]: *** [CMakeFiles/ylikuutio.dir/code/ylikuutio/network/tcp_connection.cpp.obj] Error 1
CMakeFiles/Makefile2:332: recipe for target 'CMakeFiles/ylikuutio.dir/all' failed
make[1]: *** [CMakeFiles/ylikuutio.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

However, crosscompiling Asio from Linux to Windows still does not work.

[  9%] Building CXX object CMakeFiles/ylikuutio.dir/code/ylikuutio/network/tcp_connection.cpp.obj
In file included from /home/someuser/code/ylikuutio/external/asio/asio/include/asio/associated_allocator.hpp:18:0,
                 from /home/someuser/code/ylikuutio/external/asio/asio/include/asio.hpp:18,
                 from /home/someuser/code/ylikuutio/code/ylikuutio/network/tcp_connection.hpp:2,
                 from /home/someuser/code/ylikuutio/code/ylikuutio/network/tcp_connection.cpp:1:
/home/someuser/code/ylikuutio/external/asio/asio/include/asio/detail/config.hpp:867:5: warning: #warning Please define _WIN32_WINNT or _WIN32_WINDOWS appropriately. [-Wcpp]
 #   warning Please define _WIN32_WINNT or _WIN32_WINDOWS appropriately.
     ^~~~~~~
/home/someuser/code/ylikuutio/external/asio/asio/include/asio/detail/config.hpp:868:5: warning: #warning For example, add -D_WIN32_WINNT=0x0501 to the compiler command line. [-Wcpp]
 #   warning For example, add -D_WIN32_WINNT=0x0501 to the compiler command line.
     ^~~~~~~
/home/someuser/code/ylikuutio/external/asio/asio/include/asio/detail/config.hpp:869:5: warning: #warning Assuming _WIN32_WINNT=0x0501 (i.e. Windows XP target). [-Wcpp]
 #   warning Assuming _WIN32_WINNT=0x0501 (i.e. Windows XP target).
     ^~~~~~~
In file included from /home/someuser/code/ylikuutio/external/asio/asio/include/asio/use_future.hpp:138:0,
                 from /home/someuser/code/ylikuutio/external/asio/asio/include/asio.hpp:129,
                 from /home/someuser/code/ylikuutio/code/ylikuutio/network/tcp_connection.hpp:2,
                 from /home/someuser/code/ylikuutio/code/ylikuutio/network/tcp_connection.cpp:1:
/home/someuser/code/ylikuutio/external/asio/asio/include/asio/impl/use_future.hpp: In function ‘void asio::detail::promise_invoke_and_set(std::promise<void>&, F&, Args&& ...)’:
/home/someuser/code/ylikuutio/external/asio/asio/include/asio/impl/use_future.hpp:62:6: error: invalid use of incomplete type ‘class std::promise<void>’
     p.set_value();
      ^

(the rest of the compiler error message above is cut off by me)

This is probably caused by the lack of support of `std::promise` in
MinGW's g++ (`/usr/bin/x86_64-w64-mingw32-g++`).

	modified:   w64.cmake