Bugfix: fix compiling on g++ (Debian 12.2.0-14) 12.2.0
The error was related to `EntityFactory` constructor definition and
presented itself as follows when compiling on g++ :

/home/user/ylikuutio/./code/ylikuutio/ontology/entity_factory.hpp:110:43: error: expected ‘)’ before ‘&’ token
  110 |                     yli::core::Application& application,
      |                                           ^
      |                                           )
/home/user/ylikuutio/./code/ylikuutio/ontology/entity_factory.hpp:109:40: note: to match this ‘(’
  109 |             EntityFactory<TypeEnumType>(
      |                                        ^
/home/user/ylikuutio/./code/ylikuutio/ontology/entity_factory.hpp:112:46: error: expected unqualified-id before ‘,’ token
  112 |                 : application { application },
      |                                              ^
/home/user/ylikuutio/./code/ylikuutio/ontology/entity_factory.hpp:114:13: error: expected unqualified-id before ‘{’ token
  114 |             {
      |             ^
/home/user/ylikuutio/./code/ylikuutio/ontology/entity_factory.hpp: In instantiation of ‘class yli::ontology::EntityFactory<yli::data::Datatype>’:
/home/user/ylikuutio/code/gpgpu_test/gpgpu_test.hpp:142:63:   required from here
/home/user/ylikuutio/./code/ylikuutio/ontology/entity_factory.hpp:1149:37: warning: non-static reference ‘yli::core::Application& yli::ontology::EntityFactory<yli::data::Datatype>::application’ in class without a constructor [-Wuninitialized]
 1149 |             yli::core::Application& application;
      |                                     ^~~~~~~~~~~
/home/user/ylikuutio/./code/ylikuutio/ontology/entity_factory.hpp:1150:54: warning: non-static reference ‘yli::memory::MemorySystem<yli::data::Datatype>& yli::ontology::EntityFactory<yli::data::Datatype>::memory_system’ in class without a constructor [-Wuninitialized]
 1150 |             yli::memory::MemorySystem<TypeEnumType>& memory_system;
      |                                                      ^~~~~~~~~~~~~

Tested on Debian bookworm:

$ g++ --version | head -n 1
g++ (Debian 12.2.0-14) 12.2.0

This bug did not manifest itself when compiling on Clang:

$ clang++ --version | head -n 1
Debian clang version 14.0.6