Bugfix: GitHub Actions: use `vulkan-utility-libraries-dev`.
Use `vulkan-utility-libraries-dev` for Vulkan validations layers.

This should fix the following GitHub Actions Ubuntu issue:

Package vulkan-validationlayers-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  vulkan-utility-libraries-dev

E: Package 'vulkan-validationlayers-dev' has no installation candidate
Error: Process completed with exit code 100.