Use Assimp shipped as a fake submodule, instead of the Linux package.
Reason for this is that using `find_package(assimp REQUIRED)` failed on
Travis CI for some reason.

Also, attempt to compile Assimp and `yli_convert` also when
crosscompiling from Linux to Windows. However, crosscompiling
`yli_convert` fails:

[ 99%] Building CXX object external/assimp/test/CMakeFiles/unit.dir/unit/utSceneCombiner.cpp.obj
[100%] Linking CXX executable unit.exe
[100%] Built target assimp_cmd
[100%] Built target unit
/usr/lib/gcc/x86_64-w64-mingw32/6.3-win32/../../../../x86_64-w64-mingw32/lib/libmingw32.a(lib64_libmingw32_a-crt0_c.o): In function `main':
./mingw-w64-crt/crt/crt0_c.c:18: undefined reference to `WinMain'
collect2: error: ld returned 1 exit status
CMakeFiles/yli_convert.dir/build.make:116: recipe for target 'yli_convert.exe' failed
make[2]: *** [yli_convert.exe] Error 1
CMakeFiles/Makefile2:77: recipe for target 'CMakeFiles/yli_convert.dir/all' failed
make[1]: *** [CMakeFiles/yli_convert.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[100%] Built target assimp_viewer
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

However, this is not a serious problem as `yli_convert` is going to be
used only as an offline tool in the asset pipeline.

	modified:   CMakeLists.txt
	modified:   external/CMakeLists.txt