Remove unused glog dependency.
This is due to failed submodule fetch in GitHub Actions:

From https://github.com/google/glog
 * branch            b33e3bad4c46c8a6345525fd822af355e5ef9446 -> FETCH_HEAD
Submodule path 'external/glog': checked out 'b33e3bad4c46c8a6345525fd822af355e5ef9446'
Error: error: Server does not allow request for unadvertised object f5e92d76973a7a53f517579bc95d61483bf108c0
Error: fatal: Fetched in submodule path 'external/libpng', but it did not contain f5e92d76973a7a53f517579bc95d61483bf108c0. Direct fetching of that commit failed.
Error: The process '/usr/bin/git' failed with exit code 128