Disable AppVeyor.
AppVeyor seems to fail due to limited resources on the build server.
Thus AppVeyor is not useful for building Ylikuutio.
Therefore AppVeyor will be disabled.

An example of an AppVeyor build error message:

MSBUILD : error MSB4017: The build stopped unexpectedly because of an unexpected logger failure.
Microsoft.Build.Exceptions.InternalLoggerException: The build stopped unexpectedly because of an unexpected logger failure. ---> System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
   at System.Net.WebClient.UploadDataInternal(Uri address, String method, Byte[] data, WebRequest& request)
   at System.Net.WebClient.UploadData(Uri address, String method, Byte[] data)
   at System.Net.WebClient.UploadData(String address, String method, Byte[] data)
   at Appveyor.BuildAgent.Api.RestBuildServices.AddCompilationMessage(String message, Nullable`1 category, String details, String fileName, Nullable`1 line, Nullable`1 column, String projectName, String projectFileName)
   at Appveyor.MSBuildLogger.AppveyorLogger.SendCompilationMessage(BuildMessageCategory category, String message, String code, String file, Int32 lineNumber, Int32 columnNumber, Int32 projectId)
   at Appveyor.MSBuildLogger.AppveyorLogger.eventSource_WarningRaised(Object sender, BuildWarningEventArgs e)
   at Microsoft.Build.Evaluation.ProjectCollection.ReusableLogger.WarningRaisedHandler(Object sender, BuildWarningEventArgs e)
   at Microsoft.Build.BackEnd.Logging.EventSourceSink.RaiseWarningEvent(Object sender, BuildWarningEventArgs buildEvent)
   --- End of inner exception stack trace ---
   at Microsoft.Build.Exceptions.InternalLoggerException.Throw(Exception innerException, BuildEventArgs e, String messageResourceName, Boolean initializationException, String[] messageArgs)
   at Microsoft.Build.BackEnd.Logging.EventSourceSink.RaiseWarningEvent(Object sender, BuildWarningEventArgs buildEvent)
   at Microsoft.Build.BackEnd.Logging.EventSourceSink.Consume(BuildEventArgs buildEvent)
   at Microsoft.Build.BackEnd.Logging.EventSourceSink.Consume(BuildEventArgs buildEvent, Int32 sinkId)
   at Microsoft.Build.BackEnd.Logging.EventRedirectorToSink.Microsoft.Build.Framework.IEventRedirector.ForwardEvent(BuildEventArgs buildEvent)
   at Microsoft.Build.BackEnd.Logging.CentralForwardingLogger.EventSource_AnyEventRaised(Object sender, BuildEventArgs buildEvent)
   at Microsoft.Build.BackEnd.Logging.EventSourceSink.RaiseAnyEvent(Object sender, BuildEventArgs buildEvent)
Command exited with code 1