Revert "Remove unnecessary `#include` lines."
This reverts commit fe6a7fa2b87a272b68b236d5c1e97c23dd70f7e0.

Commit fe6a7fa2b87a272b68b236d5c1e97c23dd70f7e0 causes undefined
references to SDL functions in Travis CI builds:

[100%] Linking CXX executable unit_tests_with_googletest
libylikuutio.a(audio_master.cpp.o): In function `yli::audio::AudioMaster::play_audio_callback(void*, unsigned char*, int)':
audio_master.cpp:(.text+0x48): undefined reference to `SDL_AtomicGet'
audio_master.cpp:(.text+0x66): undefined reference to `SDL_memset'
audio_master.cpp:(.text+0x80): undefined reference to `SDL_MixAudioFormat'
libylikuutio.a(audio_master.cpp.o): In function `yli::audio::AudioMaster::~AudioMaster()':
audio_master.cpp:(.text+0x24e): undefined reference to `SDL_CloseAudioDevice'
libylikuutio.a(audio_master.cpp.o): In function `yli::audio::AudioMaster::play_audio(void*, unsigned char*, int)':
audio_master.cpp:(.text+0x308): undefined reference to `SDL_AtomicGet'
audio_master.cpp:(.text+0x326): undefined reference to `SDL_memset'
audio_master.cpp:(.text+0x340): undefined reference to `SDL_MixAudioFormat'
libylikuutio.a(audio_master.cpp.o): In function `yli::audio::AudioMaster::AudioMaster(yli::ontology::Universe*)':
audio_master.cpp:(.text+0x441): undefined reference to `SDL_AtomicSet'
audio_master.cpp:(.text+0x4a9): undefined reference to `SDL_OpenAudioDevice'
audio_master.cpp:(.text+0x4b8): undefined reference to `SDL_PauseAudioDevice'
libylikuutio.a(audio_master.cpp.o): In function `yli::audio::AudioMaster::load_and_play(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
audio_master.cpp:(.text+0x6ae): undefined reference to `SDL_RWFromFile'
audio_master.cpp:(.text+0x6c8): undefined reference to `SDL_LoadWAV_RW'
audio_master.cpp:(.text+0x70c): undefined reference to `SDL_OpenAudioDevice'
audio_master.cpp:(.text+0x744): undefined reference to `SDL_AtomicSet'
audio_master.cpp:(.text+0x76d): undefined reference to `SDL_PauseAudioDevice'
audio_master.cpp:(.text+0x785): undefined reference to `SDL_Log'
audio_master.cpp:(.text+0x7d5): undefined reference to `SDL_GetError'
audio_master.cpp:(.text+0x7e6): undefined reference to `SDL_Log'
libylikuutio.a(audio_master.cpp.o): In function `yli::audio::AudioMaster::unload(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
audio_master.cpp:(.text+0x879): undefined reference to `SDL_FreeWAV'
audio_master.cpp:(.text+0x9c1): undefined reference to `SDL_PauseAudioDevice'
libylikuutio.a(audio_master.cpp.o): In function `yli::audio::AudioMaster::update()':
audio_master.cpp:(.text+0x1007): undefined reference to `SDL_AtomicGet'
audio_master.cpp:(.text+0x1023): undefined reference to `SDL_PauseAudioDevice'
libylikuutio.a(audio_master.cpp.o): In function `yli::audio::AudioMaster::play_audio_callback(void*, unsigned char*, int)':
audio_master.cpp:(.text+0xa0): undefined reference to `SDL_AtomicSet'
libylikuutio.a(audio_master.cpp.o): In function `yli::audio::AudioMaster::get_remaining_length()':
audio_master.cpp:(.text+0x2b5): undefined reference to `SDL_AtomicGet'
libylikuutio.a(audio_master.cpp.o): In function `yli::audio::AudioMaster::play_audio(void*, unsigned char*, int)':
audio_master.cpp:(.text+0x360): undefined reference to `SDL_AtomicSet'
libylikuutio.a(universe.cpp.o): In function `yli::ontology::Universe::render()':
universe.cpp:(.text+0x12b): undefined reference to `SDL_GL_SwapWindow'
libylikuutio.a(universe.cpp.o): In function `yli::ontology::Universe::~Universe()':
universe.cpp:(.text+0x3f0): undefined reference to `SDL_Quit'
libylikuutio.a(universe.cpp.o): In function `yli::ontology::Universe::render_without_changing_depth_test()':
universe.cpp:(.text+0x8fe): undefined reference to `SDL_GL_SwapWindow'
libylikuutio.a(universe.cpp.o): In function `yli::ontology::Universe::compute_delta_time()':
universe.cpp:(.text+0xdce): undefined reference to `SDL_GetTicks'
universe.cpp:(.text+0xe01): undefined reference to `SDL_GetTicks'
libylikuutio.a(ylikuutio_sdl.cpp.o): In function `yli::sdl::init_sdl()':
ylikuutio_sdl.cpp:(.text+0xa): undefined reference to `SDL_Init'
ylikuutio_sdl.cpp:(.text+0x1d): undefined reference to `SDL_GL_SetAttribute'
ylikuutio_sdl.cpp:(.text+0x2c): undefined reference to `SDL_GL_SetAttribute'
libylikuutio.a(ylikuutio_sdl.cpp.o): In function `yli::sdl::create_context(SDL_Window*)':
ylikuutio_sdl.cpp:(.text+0x9d): undefined reference to `SDL_GL_CreateContext'
libylikuutio.a(ylikuutio_sdl.cpp.o): In function `yli::sdl::flush_sdl_event_queue()':
ylikuutio_sdl.cpp:(.text+0x154): undefined reference to `SDL_PollEvent'
libylikuutio.a(ylikuutio_sdl.cpp.o): In function `yli::sdl::create_window(int, int, char const*, bool)':
ylikuutio_sdl.cpp:(.text+0x82): undefined reference to `SDL_CreateWindow'
libylikuutio.a(ylikuutio_sdl.cpp.o): In function `yli::sdl::set_window_size(SDL_Window*, int, int)':
ylikuutio_sdl.cpp:(.text+0xf1): undefined reference to `SDL_SetWindowSize'
libylikuutio.a(ylikuutio_sdl.cpp.o): In function `yli::sdl::set_window_windowed(SDL_Window*)':
ylikuutio_sdl.cpp:(.text+0x103): undefined reference to `SDL_SetWindowFullscreen'
libylikuutio.a(ylikuutio_sdl.cpp.o): In function `yli::sdl::make_context_current(SDL_Window*, void*)':
ylikuutio_sdl.cpp:(.text+0x111): undefined reference to `SDL_GL_MakeCurrent'
libylikuutio.a(ylikuutio_sdl.cpp.o): In function `yli::sdl::set_swap_interval(int)':
ylikuutio_sdl.cpp:(.text+0x121): undefined reference to `SDL_GL_SetSwapInterval'
libylikuutio.a(time.cpp.o): In function `yli::time::get_time()':
time.cpp:(.text+0x5): undefined reference to `SDL_GetTicks'
collect2: error: ld returned 1 exit status
CMakeFiles/unit_tests_with_googletest.dir/build.make:662: recipe for target 'unit_tests_with_googletest' failed
make[2]: *** [unit_tests_with_googletest] Error 1
CMakeFiles/Makefile2:77: recipe for target 'CMakeFiles/unit_tests_with_googletest.dir/all' failed
make[1]: *** [CMakeFiles/unit_tests_with_googletest.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
travis_time:end:073ac1ef:start=1589666930749775817,finish=1589667380732150792,duration=449982374975,event=script
[0K[31;1mThe command "make -j 4" exited with 2.[0m
travis_time:start:2e436880
[0K$ ./unit_tests_with_googletest
/home/travis/.travis/functions: line 109: ./unit_tests_with_googletest: No such file or directory
travis_time:end:2e436880:start=1589667380737314473,finish=1589667380755800952,duration=18486479,event=script
[0K[31;1mThe command "./unit_tests_with_googletest" exited with 127.[0m

Done. Your build exited with 1.